name: Build Debug Cache

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
    inputs:
      features:
        description: "List of features to enable"
        required: false
        default: ""
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "tests/fixtures/**"
      - "static/**"
      - ".sqlx/**"

env:
  CACHE_SHARED_KEY: stable-release
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  build_debug_cache:
    name: Build Debug cache
    runs-on: ubuntu-22.04
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
        with:
          toolchain: 1.88

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Set up dependencies
        uses: taiki-e/install-action@cfdb446e391c69574ebc316dfb7d7849ec12b940 # v2.68.8
        with:
          tool: cargo-llvm-cov@0.6.14

      - name: Build Debug binaries for cache
        run: |
          source <(cargo llvm-cov show-env --export-prefix)
          cargo build --features dev

      - name: Rust Cache - Save shared key
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ env.CACHE_SHARED_KEY }}-${{ runner.os }}--${{ hashFiles('**/Cargo.lock') }}


